=== projektD-Klaus/contact-motion-planning-master/examples/rlsg/rlsg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="body">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="body" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rlsg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scene"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scene">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="model" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="href" type="xs:anyURI" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/lshape-6d_maze2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="lshape-6d_maze2.wrl">
		<model name="lshape-6d">
			<body name="link0" />
			<body name="link1" />
			<body name="link2" />
			<body name="link3" />
			<body name="link4" />
			<body name="link5" />
			<body name="body1" />
		</model>
		<model name="maze2">
			<body name="" />
		</model>
	</scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/CFP_Scene_1.convex.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="CFP_Scene_1.convex.wrl">
		<model name="Robot_KR60-3_WithGripper">
			<body name="link0"/>
			<body name="link1"/>
			<body name="link2"/>
			<body name="link3"/>
			<body name="link4"/>
			<body name="link5"/>
			<body name="link6"/>
		</model>
		<model name="TestRoom">
			<body name="wall"/>
			<body name="floor"/>
			<body name="column1"/>
			<body name="column2"/>
			<body name="column3"/>
			<!--<body name="halfcolumn"/>-->
			<body name="hanger"/>
			<body name="deposittable"/>
		</model>
	</scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/uman_wall2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="uman_wall2.wrl">
		<model name="uman">
			<body name="link0" />
			<body name="link1" />
			<body name="link2" />
			<body name="link3" />
			<body name="link4" />
			<body name="link5" />
			<body name="link6" />
			<body name="link7" />
			<body name="link8" />
			<body name="link9" />
			<body name="link10" />
		</model>
		<model name="wall2">
			<body name="" />
		</model>
	</scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/mitsubishi-rv6sl_boxes.convex.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="mitsubishi-rv6sl_boxes.convex.wrl">
		<model name="mitsubishi-rv6sl">
			<body name="link0"/>
			<body name="link1"/>
			<body name="link2"/>
			<body name="link3"/>
			<body name="link4"/>
			<body name="link5"/>
			<body name="link6"/>
		</model>
		<model name="boxes">
			<body name=""/>
		</model>
	</scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/2d-gripper-maze.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
  <scene href="2d-gripper-maze.wrl">
    <model name="box-2d-050505">
      <body name="link0" />
      <body name="link1" />
      <body name="body1" />
    </model>
    <model name="boxes">
      <body name=""/>
    </model>
  </scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/jahir.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="jahir.wrl">
		<model name="rv6sl">
			<body name="link0"/>
			<body name="link1"/>
			<body name="link2"/>
			<body name="link3"/>
			<body name="link4"/>
			<body name="link5"/>
			<body name="link6"/>
		</model>
		<model name="jahir">
			<body name="base"/>
			<body name="table"/>
			<body name="green"/>
			<body name="blue"/>
			<body name="obstacles1"/>
			<!--<body name="obstacles2"/>-->
		</model>
	</scene>
</rlsg>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlsg/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="example.wrl">
		<model name="robot">
			<body name="link0"/>
			<body name="link1"/>
			<body name="link2"/>
		</model>
		<model name="obstacles">
			<body name="floor"/>
			<body name="obstacle1"/>
			<body name="obstacle2"/>
			<body name="obstacle3"/>
			<body name="obstacle4"/>
		</model>
	</scene>
</rlsg>
