=== projektD-Klaus/contact-motion-planning-master/examples/rlkin/rlkin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="elementType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="frame" type="frameType"/>
	<xs:complexType name="frameType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jointType">
		<xs:complexContent>
			<xs:extension base="transformType">
				<xs:sequence>
					<xs:element name="center" type="xs:double" minOccurs="0"/>
					<xs:element name="dh">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="d" type="xs:double"/>
								<xs:element name="theta" type="xs:double"/>
								<xs:element name="a" type="xs:double"/>
								<xs:element name="alpha" type="xs:double"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="max" type="xs:double" minOccurs="0"/>
					<xs:element name="min" type="xs:double" minOccurs="0"/>
					<xs:element name="offset" type="xs:double" minOccurs="0"/>
					<xs:element name="speed" type="xs:double" minOccurs="0"/>
					<xs:element name="wraparound" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="kinematics" type="kinematicsType"/>
	<xs:complexType name="kinematicsType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element ref="world" minOccurs="1"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="frame" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="prismatic" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="revolute" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="transform" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="link">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="frameType">
					<xs:sequence>
						<xs:element name="ignore" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="idref" type="xs:IDREF"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="prismatic" type="prismaticType"/>
	<xs:complexType name="prismaticType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="puma" type="pumaType"/>
	<xs:complexType name="pumaType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element ref="world" minOccurs="1"/>
			<xs:element ref="transform" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="transform" minOccurs="1"/>
			<xs:element ref="frame" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="revolute" type="revoluteType"/>
	<xs:complexType name="revoluteType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="rhino" type="rhinoType"/>
	<xs:complexType name="rhinoType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element ref="world" minOccurs="1"/>
			<xs:element ref="transform" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="revolute" minOccurs="1"/>
			<xs:element ref="link" minOccurs="1"/>
			<xs:element ref="transform" minOccurs="1"/>
			<xs:element ref="frame" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="rlkin">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="kinematics"/>
				<xs:element ref="puma"/>
				<xs:element ref="rhino"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="transform" type="transformType"/>
	<xs:complexType name="transformType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="frame">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="a">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="b">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="world" type="worldType"/>
	<xs:complexType name="worldType">
		<xs:complexContent>
			<xs:extension base="frameType"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlkin/staeubli-tx90l.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlkin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlkin.xsd">
	<puma>
		<manufacturer>St√§ubli</manufacturer>
		<name>TX-90L</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</world>
		<transform id="base">
			<frame>
				<a idref="world"/>
				<b idref="link0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<link id="link0">
			<ignore/>
			<ignore idref="link1"/>
		</link>
		<revolute id="joint0">
			<frame>
				<a idref="link0"/>
				<b idref="link1"/>
			</frame>
			<dh>
				<d>0.478</d>
				<theta>0</theta>
				<a>0.05</a>
				<alpha>-90</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
			<speed>215</speed>
		</revolute>
		<link id="link1">
			<ignore idref="link0"/>
			<ignore idref="link2"/>
		</link>
		<revolute id="joint1">
			<frame>
				<a idref="link1"/>
				<b idref="link2"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>-90</theta>
				<a>0.5</a>
				<alpha>0</alpha>
			</dh>
			<max>147.5</max>
			<min>-130</min>
			<speed>170</speed>
		</revolute>
		<link id="link2">
			<ignore idref="link1"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
		</link>
		<revolute id="joint2">
			<frame>
				<a idref="link2"/>
				<b idref="link3"/>
			</frame>
			<dh>
				<d>0.05</d>
				<theta>-90</theta>
				<a>0</a>
				<alpha>-90</alpha>
			</dh>
			<max>145</max>
			<min>-145</min>
			<speed>255</speed>
		</revolute>
		<link id="link3">
			<ignore idref="link2"/>
			<ignore idref="link4"/>
		</link>
		<revolute id="joint3">
			<frame>
				<a idref="link3"/>
				<b idref="link4"/>
			</frame>
			<dh>
				<d>0.55</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>270</max>
			<min>-270</min>
			<speed>430</speed>
		</revolute>
		<link id="link4">
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link5"/>
			<ignore idref="link6"/>
		</link>
		<revolute id="joint4">
			<frame>
				<a idref="link4"/>
				<b idref="link5"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>180</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>140</max>
			<min>-115</min>
			<speed>350</speed>
		</revolute>
		<link id="link5">
			<ignore idref="link4"/>
			<ignore idref="link6"/>
		</link>
		<revolute id="joint5">
			<frame>
				<a idref="link5"/>
				<b idref="link6"/>
			</frame>
			<dh>
				<d>0.1</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>0</alpha>
			</dh>
			<max>270</max>
			<min>-270</min>
			<speed>600</speed>
		</revolute>
		<link id="link6">
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<transform id="tool">
			<frame>
				<a idref="link6"/>
				<b idref="tcp"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<frame id="tcp"/>
	</puma>
</rlkin>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlkin/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlkin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlkin.xsd">
	<kinematics>
		<manufacturer></manufacturer>
		<name>Example</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</world>
		<transform id="base">
			<frame>
				<a idref="world"/>
				<b idref="link0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>90</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<link id="link0">
			<ignore/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
		</link>
		<revolute id="joint0">
			<frame>
				<a idref="link0"/>
				<b idref="link1"/>
			</frame>
			<dh>
				<d>0.1</d>
				<theta>0</theta>
				<a>0.3</a>
				<alpha>0</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
		</revolute>
		<link id="link1">
			<ignore idref="link0"/>
			<ignore idref="link2"/>
		</link>
		<revolute id="joint1">
			<frame>
				<a idref="link1"/>
				<b idref="link2"/>
			</frame>
			<dh>
				<d>0.05</d>
				<theta>0</theta>
				<a>0.33</a>
				<alpha>0</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
		</revolute>
		<link id="link2">
			<ignore idref="link0"/>
			<ignore idref="link1"/>
		</link>
		<transform id="tool">
			<frame>
				<a idref="link2"/>
				<b idref="tcp"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>-0.025</z>
			</translation>
		</transform>
		<frame id="tcp"/>
	</kinematics>
</rlkin>
