=== projektD-Klaus/contact-motion-planning-master/examples/rlmdl/rlmdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="body">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="frameType">
					<xs:sequence>
						<xs:element name="cm" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="x" type="xs:double" minOccurs="0"/>
									<xs:element name="y" type="xs:double" minOccurs="0"/>
									<xs:element name="z" type="xs:double" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="i" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="xx" type="xs:double" minOccurs="0"/>
									<xs:element name="yy" type="xs:double" minOccurs="0"/>
									<xs:element name="zz" type="xs:double" minOccurs="0"/>
									<xs:element name="yz" type="xs:double" minOccurs="0"/>
									<xs:element name="xz" type="xs:double" minOccurs="0"/>
									<xs:element name="xy" type="xs:double" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ignore" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="idref" type="xs:IDREF"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="m" type="xs:double" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="elementType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="fixed" type="fixedType"/>
	<xs:complexType name="fixedType">
		<xs:complexContent>
			<xs:extension base="transformType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="frame" type="frameType"/>
	<xs:complexType name="frameType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jointType">
		<xs:complexContent>
			<xs:extension base="transformType">
				<xs:sequence>
					<xs:element name="axis">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="max" type="xs:double" minOccurs="0"/>
					<xs:element name="min" type="xs:double" minOccurs="0"/>
					<xs:element name="offset" type="xs:double" minOccurs="0"/>
					<xs:element name="speed" type="xs:double" minOccurs="0"/>
					<xs:element name="wraparound" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="model" type="modelType"/>
	<xs:complexType name="modelType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element ref="world" minOccurs="1"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="body" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="fixed" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="frame" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="prismatic" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="revolute" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="prismatic" type="prismaticType"/>
	<xs:complexType name="prismaticType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="revolute" type="revoluteType"/>
	<xs:complexType name="revoluteType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="rlmdl">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="model"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="transformType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="frame">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="a">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="b">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="world" type="worldType"/>
	<xs:complexType name="worldType">
		<xs:complexContent>
			<xs:extension base="frameType">
				<xs:sequence>
					<xs:element name="g">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== projektD-Klaus/contact-motion-planning-master/rl-examples-0.6.2/rlmdl/kuka-kr16-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlmdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlmdl.xsd">
	<model>
		<manufacturer>Kuka</manufacturer>
		<name>KR 16-2</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
			<g>
				<x>0</x>
				<y>0</y>
				<z>9.86055</z>
			</g>
		</world>
		<body id="body0">
			<ignore/>
			<ignore idref="body1"/>
		</body>
		<frame id="frame0"/>
		<body id="body1">
			<ignore idref="body0"/>
			<ignore idref="body2"/>
		</body>
		<frame id="frame1"/>
		<body id="body2">
			<ignore idref="body1"/>
			<ignore idref="body3"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame2"/>
		<body id="body3">
			<ignore idref="body2"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame3"/>
		<body id="body4">
			<ignore idref="body2"/>
			<ignore idref="body3"/>
			<ignore idref="body5"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame4"/>
		<body id="body5">
			<ignore idref="body4"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame5"/>
		<body id="body6">
			<ignore idref="body4"/>
			<ignore idref="body5"/>
		</body>
		<frame id="frame6"/>
		<fixed id="fixed0">
			<frame>
				<a idref="world"/>
				<b idref="body0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="A1">
			<frame>
				<a idref="body0"/>
				<b idref="frame0"/>
			</frame>
			<axis>
				<x>0</x>
				<y>0</y>
				<z>-1</z>
			</axis>
			<max>185</max>
			<min>-185</min>
			<speed>156</speed>
		</revolute>
		<fixed id="fixed1">
			<frame>
				<a idref="frame0"/>
				<b idref="body1"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.26</x>
				<y>0</y>
				<z>0.675</z>
			</translation>
		</fixed>
		<revolute id="A2">
			<frame>
				<a idref="body1"/>
				<b idref="frame2"/>
			</frame>
			<axis>
				<x>0</x>
				<y>1</y>
				<z>0</z>
			</axis>
			<max>35</max>
			<min>-155</min>
			<speed>156</speed>
		</revolute>
		<fixed id="fixed3">
			<frame>
				<a idref="frame2"/>
				<b idref="body2"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.715</z>
			</translation>
		</fixed>
		<revolute id="A3">
			<frame>
				<a idref="body2"/>
				<b idref="frame3"/>
			</frame>
			<axis>
				<x>0</x>
				<y>1</y>
				<z>0</z>
			</axis>
			<max>154</max>
			<min>-130</min>
			<speed>156</speed>
		</revolute>
		<fixed id="fixed4">
			<frame>
				<a idref="frame3"/>
				<b idref="body3"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.67</x>
				<y>0</y>
				<z>-0.035</z>
			</translation>
		</fixed>
		<revolute id="A4">
			<frame>
				<a idref="body3"/>
				<b idref="frame4"/>
			</frame>
			<axis>
				<x>-1</x>
				<y>0</y>
				<z>0</z>
			</axis>
			<max>350</max>
			<min>-350</min>
			<speed>330</speed>
		</revolute>
		<fixed id="fixed5">
			<frame>
				<a idref="frame4"/>
				<b idref="body4"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="A5">
			<frame>
				<a idref="body4"/>
				<b idref="frame5"/>
			</frame>
			<axis>
				<x>0</x>
				<y>1</y>
				<z>0</z>
			</axis>
			<max>130</max>
			<min>-130</min>
			<speed>330</speed>
		</revolute>
		<fixed id="fixed6">
			<frame>
				<a idref="frame5"/>
				<b idref="body5"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="A6">
			<frame>
				<a idref="body5"/>
				<b idref="frame6"/>
			</frame>
			<axis>
				<x>-1</x>
				<y>0</y>
				<z>0</z>
			</axis>
			<max>350</max>
			<min>-350</min>
			<speed>615</speed>
		</revolute>
		<fixed id="fixed9">
			<frame>
				<a idref="frame6"/>
				<b idref="body6"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.115</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
	</model>
</rlmdl>
